# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:}
cloudinary.api-key=${CLOUDINARY_API_KEY:}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:}

# Firebase Admin
firebase.project-id=${FIREBASE_PROJECT_ID:}
firebase.service-account.path=${FIREBASE_SERVICE_ACCOUNT_PATH:}
firebase.service-account.base64=${FIREBASE_SERVICE_ACCOUNT_BASE64:}

# Limite maximo por fichero
spring.servlet.multipart.max-file-size=10MB
# Limite maximo por peticion
spring.servlet.multipart.max-request-size=10MB
